version: "3.8"
services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Redstar98
      - MYSQL_DATABASE=database
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8081:8080
    volumes:
      - ./images:/app/images
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/database?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "Redstar98",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
  angular-service:
    container_name: angular-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4201:4200
    links:
      - app
    command: >
      bash -c "npm start"
      